### PR TITLE
Various plugin-related fixes

### LINKED ISSUE #16: Include path issue for BiFs
For the plugin feature, including a header from the plugin sources doesn't work in BiF files:
```
module SomePlugin;

%%{
#include "MyPluginHeader.h"
%%}
```
@awelzel found this to be an include path issue: BiFs seems to be looking at `src` while the sources are in `plugin/src`.

### PR DESCRIPTION
**Pull request by ckreibich**
- Add the plugin tree's src directory to the include path so header files can actually be included
- Remove old CAF configure code that was already marked for removal
- Remove hardwired `make` from the `build_command` to support other cmake generators (@mavam, fyi!)
- Add BiF testcase
- Bump cmake requirement to 3.15, to align with Zeek's
- Add compatibility around Zeek 6's handling of `local_orig`/`local_resp` in conn.log

Resolves #16.

### CODE REVIEW

**Comment by ckreibich** [comment]
This is all for the soon-to-be legacy cmake plugin API, so the test for the nightly fails as we iron things out. I suspect we'll need something like
```
if(COMMAND zeek_add_plugin)
    # New code
else()
   # Current code
endif()
```
in CMakeLists.txt for a long time. I'll put this into draft mode for now.

**Comment by Neverlord** [comment]
```
if(COMMAND zeek_add_plugin)
    # New code
else()
   # Current code
endif()
```

Wouldn't that basically duplicate the entire plugin setup? My gut feeling is that this makes it all too easy to just update one part of the tree manually, for example when adding a new source file, and forgetting the other half. And then it works only on some of the supported Zeek versions.

Do we have a policy for how long we support a certain API? We introduce the new syntax in Zeek 6 and it'll only work on that release. So maybe we could just add the new API (and we already use it internally) and give the template a parameter for the minimum Zeek version? That way, a plugin that needs Zeek 6 anyways can start using the new API, e.g. via `--min-zeek=6.0`. Other plugins continue to use the old functions. Eventually, we can deprecate the old versions (Zeek 7/8?) and remove them after some grace period (at least one major version, probably). But I'd rather avoid using both APIs in the same CMake file.

**Comment by ckreibich** [comment]
@Neverlord, @bbannier, all good points. I don't think this PR is a good place for this, so I've created a discussion over [here](https://github.com/zeek/zeek/discussions/2963).

**Comment by ckreibich** [comment]
I think is a reasonable set of changes for this PR so I've marked it ready for review. I'll look into a BinPAC scenario as well modernization for Zeek 6's cmake infrastructure separately.

**Review by timwoj — APPROVED** [review]

**Pull request merged**
